name: kupol_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  awesome_dialog: ^2.1.2
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  easy_dynamic_theme: ^2.2.0
  image_picker: ^0.8.4+4
  provider: ^6.0.1
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.0.0+2
  extended_masked_text: ^2.3.1
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/logo/app_logo_ios.jpg"
  image_path_android: "lib/assets/logo/app_logo_ios.jpg"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/logo/

  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: lib/assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: lib/assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/OpenSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/OpenSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: lib/assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: lib/assets/fonts/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 900